# Generated by Django 5.2.17 on 2026-08-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Carta')),
                ('juego', models.CharField(choices=[('Pokemon', 'Pokémon'), ('MTG', 'Magic: The Gathering'), ('Yugioh', 'Yu-Gi-Oh!'), ('Lorcana', 'Lorcana'), ('OnePiece', 'One Piece')], max_length=20, verbose_name='Juego TCG')),
                ('coleccion', models.CharField(max_length=100, verbose_name='Edición / Colección')),
                ('rareza', models.CharField(max_length=50, verbose_name='Rareza')),
                ('estado', models.CharField(choices=[('NM', 'Near Mint (NM)'), ('LP', 'Lightly Played (LP)'), ('MP', 'Moderately Played (MP)'), ('HP', 'Heavily Played (HP)')], default='NM', max_length=2, verbose_name='Estado de Conservación')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Estimado ($)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
        ),
    ]
